import { Geist, Geist_Mono ,Anton,Poppins,Plus_Jakarta_Sans} from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], 
  variable: '--font-poppins',
});
const anton = Anton({
  subsets: ['latin'],
  weight: '400', // Anton only has 400
});
export const plusJakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weights: ['400', '500', '600', '700', '800'],
  variable: '--font-plus-jakarta',
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}   ${poppins.variable}  ${anton.variable}  ${plusJakarta.variable}`}>
        {children}
      </body>
    </html>
  );
}
